/* export interface AllProducts {
    id: number;
    product_no: string;
    product_name: string;
    product_description: string;
    product_price: number;
    product_discount: number;
    product_featured: boolean;
    product_sizes: string;
    product_colors: string;
    units_in_stock: number;
    product_images: string;
    product_promo: boolean;
    category_id: number;
    supplier_id: number;
    suggested_sales_price: number;
    units_on_order: number;
    reorder_level: number;
    product_available: boolean;
    unit_price: number;
} */

export interface AllProducts {
    available: number;
    category_description: string;
    category_id: number;
    category_name: string;
    city: string;
    company_address: string;
    company_name: string;
    contact_fname: string;
    contact_lname: string;
    contact_title: string;
    cost_price: number;
    country: string;
    customer_id: number;
    email: string;
    image: string;
    image_id: number;
    phone: string;
    postal_code: string;
    product_colors: string;
    product_description: string;
    product_discount: number;
    product_featured: boolean;
    product_id: number;
    product_name: string;
    product_no: string;
    product_price: number;
    product_promo: boolean;
    product_sizes: string;
    reorder_level: number;
    subcategory_description: string;
    subcategory_id: number;
    subcategory_name: string;
    supplier_id: number;
    toggle: boolean;
    unit_price: number;
    units_in_stock: number;
    units_on_order: number;

}
